- name: catalogue 
  hosts: catalogue
  become: yes
  tasks: 
  - name: enable and disable nodejs
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name: install nodejs
    ansible.builtin.package:
     name: install nodejs
     state: present

  - name: create user roboshop
    ansible.builtin.user:
     name: roboshop

  - name: create app
    ansible.builtin.file: 
     path: /app
     state: directory

  - name: download catalouge application 
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue.zip
      dest: /tmp 
  
  - name: extract catalogue applications
    ansible.builtin.unarchive:  
      src: /tmp/catalogue.zip 
      dest: /app
      remote_src: yes

  - name: install dependencies
    ansible.builtin.command: npm install 
    args:
      chdir: /app
  
  - name: copy catalogue.service
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: daemon reload
    ansible.builtin.systemd_servie:
      daemon_reload: true
  
  - name: start and enable 
    ansible.builtin.service:
      name: catalogue
      service: started
      enabled: yes
  - name: copy mongodb.repo
    ansible.builtin.copy: 
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb client
    ansible.builtin.package:
      name: mongodb-org-shell
      state: present
  
  - name: loda catalouge data 
    ansible.builtin.command: mongo --host mongodb.manacars.shop </app/schema/catalogue.js