- name: mysql
  hosts: mysql
  become: yes
  tasks: 
  - name: disable mysql -y 
    ansible.builtin.command: dnf module disable mysql -y 

  - name: copy mongo.repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mysql.repo
    
  - name: install mysql.repo
    ansible.builtin.command: dnf install mysql-community-server -y
  
  - name: start and enabled mysql 
    ansible.builtin.systemd_service:
      name: mysqld
      state: started
      enabled: yes

  - name: setup root password
    ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1