- name: payment component
  hosts: payment
  become: yes
  tasks:
  - name: install python
    ansible.builtin.package:
     name: "{{item}}"
     state: present
    loop:
    - python36
    - gcc 
    - python3-devel

  - name: create roboshop user
    ansible.builtin.user:
      name: roboshop

  - name: disable app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: crate directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download payment application
    ansible.buitlin.get_url:
      url:  https://roboshop-artifacts.s3.amazonaws.com/payment.zip 
      dest: /tmp

  - name: extract payment.zip
    ansible.builtin.unarchive:
      src: /tmp/payment.zip
      dest: /app

  - name: install requirments
    ansible.builtin.command: pip3.6 install -r requirements.txt
    args:   
      chdir: /app

  - name: copy payment.service
    ansible.builtin.copy:
      src: payment.service
      dest: /etc/systemd/system/payment.service

  - name: daemon reload service
    ansible.builtin.systemd_service:
     daemon_reload: true

  - name: start and enable 
    ansible.builtin.service: 
      name: payment
      state: started
      enabled: yes
