- name: rabbitmq component
  hosts: rabbitmq
  become: yes
  tasks:
  - name: install denpendencies
    ansible.builtin.command: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash


  - name: install yum repos
    ansible.builtin.command: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

  - name: install rabbitmq
    ansible.builtin.package:
      name: rabbitmq-server
      state: present
  
  - name: start and enable rabbitmq
    ansible.builtin.service: 
      name: rabbitmq-server
      state: started
      enabled: yes

  - name: create roboshop user
    ansible.builtin.command: rabbitmqctl add_user roboshop roboshop123

  - name: set permissions
    ansible.builtin.command: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"